//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public int IdAu { get; set; }
        public string IdTp { get; set; }
        public string Email { get; set; }
        public string NameAu { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<int> Time { get; set; }
    
        public virtual TopicOfLecture TopicOfLecture { get; set; }
    }
}
